---
- name: debian | couchbase release
  ansible.builtin.apt:
    deb: "https://packages.couchbase.com/releases/couchbase-release/couchbase-release-{{ couchbase_release_version }}-amd64.deb"
    state: present

# https://forums.couchbase.com/t/installation-couchbase-server-7-1-on-debian-11/33563/2
- name: remove couchbase-lite-repo from apt (this repository isn't required and breaks install)
  ansible.builtin.lineinfile:
    dest: /etc/apt/sources.list.d/couchbase.list
    state: absent
    regexp: "^deb http:\/\/packages.couchbase.com\/releases\/couchbase-lite-repo"

- name: debian | couchbase server
  ansible.builtin.apt:
    name: "couchbase-server={{ couchbase_server_version }}-1"
    update_cache: true
    state: present
