---
- name: cluster | wait for nodes to be healthy
  ansible.builtin.uri:
    url: http://127.0.0.1:8091/nodes/self
    method: 'GET'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
  register: node
  retries: 5
  delay: 10
  until:
    - node.status == 200
    - node.json.status == "healthy"

- name: cluster | check cluster nodes were initialized already
  ansible.builtin.uri:
    url: http://127.0.0.1:8091//pools/default
    method: 'GET'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
    status_code:
      - 200
      - 404
  register: pool

- name: cluster | init one node
  ansible.builtin.include_tasks: cluster/init.yml
  when:
    - inventory_hostname == init_node
    - pool.status == 404

- name: cluster | add node to the cluster
  ansible.builtin.include_tasks: cluster/node.yml
  when:
    - inventory_hostname != init_node
    - pool.status == 404

- name: cluster | rebalance
  ansible.builtin.include_tasks: cluster/rebalance.yml
  when: inventory_hostname == init_node

- name: cluster | manage external address
  ansible.builtin.uri:
    url: "http://127.0.0.1:8091/node/controller/setupAlternateAddresses/external"
    method: 'PUT'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
    body:
      hostname: "{{ couchbase_external_address }}"
    body_format: form-urlencoded
  when: couchbase_external_address is defined
