---
- name: configure | get buckets information
  ansible.builtin.uri:
    url: http://127.0.0.1:8091/pools/default/buckets
    method: 'GET'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
  register: buckets

- name: configure | create buckets
  ansible.builtin.uri:
    url: http://127.0.0.1:8091/pools/default/buckets
    method: 'POST'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
    body:
      name: "{{ item.name }}"
      bucketType: "{{ item.bucketType | d(__couchbase_bucket_defaults.bucketType) }}"
      ramQuota: "{{ item.ramQuota | d(__couchbase_bucket_defaults.ramQuota) }}"
      storageBackend: "{{ item.storageBackend | d(__couchbase_bucket_defaults.storageBackend) }}"
      replicaNumber: "{{ item.replicaNumber | d(__couchbase_bucket_defaults.replicaNumber) }}"
      compressionMode: "{{ item.compressionMode | d(__couchbase_bucket_defaults.compressionMode) }}"
      flushEnabled: "{{ item.flushEnabled | d(__couchbase_bucket_defaults.flushEnabled) }}"
    body_format: form-urlencoded
    status_code:
      - 202
  loop: "{{ couchbase_buckets }}"
  when: item.name not in buckets['json'] | map(attribute='name') | list

- name: configure | create primary indexes
  ansible.builtin.uri:
    url: http://127.0.0.1:8093/query/service
    method: 'POST'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
    force_basic_auth: true
    body:
      statement: "CREATE PRIMARY INDEX `idx_{{ item.name }}_primary` IF NOT EXISTS ON `{{ item.name }}`"
    body_format: form-urlencoded
  loop: "{{ couchbase_buckets }}"
  when: couchbase_create_primary_indexes|bool

- name: configure | execute custom queries
  ansible.builtin.uri:
    url: http://127.0.0.1:8093/query/service
    method: 'POST'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
    force_basic_auth: true
    body:
      statement: "{{ item }}"
    body_format: form-urlencoded
  loop: "{{ couchbase_custom_queries }}"

- name: configure | create/update users
  ansible.builtin.uri:
    url: "http://127.0.0.1:8091/settings/rbac/users/local/{{ item.name }}"
    method: 'PUT'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
    body:
      password: "{{ item.password }}"
      roles: "{{ item.roles | d(__couchbase_user_defaults.roles) }}"
    body_format: form-urlencoded
  loop: "{{ couchbase_users }}"
