---
- name: main | install packages
  ansible.builtin.include_tasks: "install/{{ ansible_os_family }}.yml"

- name: main | create systemd directory
  ansible.builtin.file:
    path: /etc/systemd/system/couchbase-server.service.d
    state: directory
    mode: '0755'

- name: main | adjust nproc limit for couchbase service
  ansible.builtin.copy:
    content: |
      [Service]
      LimitNPROC=16384
    dest: /etc/systemd/system/couchbase-server.service.d/limits.conf
    mode: '0644'
  notify: restart couchbase service

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: main | define init node
  ansible.builtin.set_fact:
    init_node: "{{ ansible_play_hosts | sort | first }}"

- name: main | configure cluster
  ansible.builtin.include_tasks: cluster.yml
  when: not ansible_check_mode

- name: main | configure buckets and users
  ansible.builtin.include_tasks: configure.yml
  when:
    - inventory_hostname == init_node
    - not ansible_check_mode
