---
- name: cluster/node | join cluster
  ansible.builtin.uri:
    url: "http://127.0.0.1:8091/controller/addNode"
    method: 'POST'
    user: "{{ couchbase_admin_user }}"
    password: "{{ couchbase_admin_password }}"
    body:
      hostname: "{{ couchbase_host_address }}"
      user: "{{ couchbase_admin_user }}"
      password: "{{ couchbase_admin_password }}"
      services: "{{ couchbase_services }}"
    body_format: form-urlencoded
  delegate_to: "{{ init_node }}"
