---
- name: side effects
  hosts: all
  tasks:
    - name: install sample bucket
      ansible.builtin.uri:
        url: http://127.0.0.1:8091/sampleBuckets/install
        method: 'POST'
        user: 'admin'
        password: 'password'
        body:
          - travel-sample
        body_format: json
        status_code:
          - 202
      run_once: true
    - name: provide alice access to this bucket
      ansible.builtin.uri:
        url: http://127.0.0.1:8091/settings/rbac/users/local/alice
        method: 'PUT'
        user: 'admin'
        password: 'password'
        body:
          roles: 'bucket_full_access[travel-sample]'
        body_format: form-urlencoded
      run_once: true
